services:
  - type: web
    name: startlinker-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: REACT_APP_API_URL
        value: https://startlinker-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000