services:
  - type: web
    name: startlinker-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        value: https://startlinker-backend.onrender.com