services:
  - type: web
    name: startlinker-frontend
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20.17.0"
      - key: REACT_APP_API_URL
        value: https://startlinker-backend.onrender.com
      - key: NODE_ENV
        value: production